name:                algorithms
version:             0.1.0.0
github:              "ValerianClerc/algorithms"
license:             BSD3
author:              "Valerian Clerc"
maintainer:          "valerian.clerc@gmail.com"
copyright:           "2021 Valerian Clerc"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/ValerianClerc/algorithms#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  spec:
    defaults: hspec/hspec@master
    dependencies:
    - algorithms
